# -------------------------------------------------------
#!/bin/bash
# -------------------------------------------------------
# Copyright (c) [2022] Nadege Lemperiere
# All rights reserved
# -------------------------------------------------------
# Pull request pipeline for robotframework keywords
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 19 november 2022
# -------------------------------------------------------

name: Keywords Pull Request Pipeline

on:
    pull_request:
        types: [ assigned, opened, synchronize, reopened ]

jobs:


    check:
        name: Analyze Package
        runs-on: ubuntu-latest
        container:
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://nadegelemperiere-docker/terraform-python-awscli:latest
              with:
                args: pip install -r requirements-test.txt --target site-packages

            - name: Linting module
              uses: docker://nadegelemperiere-docker/terraform-python-awscli:latest
              with:
                args: pylint aws_iac_keywords

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/python@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                PYTHONPATH: /github/workspace/site-packages
              with:
                args: --sarif-file-output=snyk.sarif --file=setup.py

            - name: Run pip-audit to check for vulnerabilities
              uses: docker://nadegelemperiere-docker/terraform-python-awscli:latest
              with:
                args: pip-audit -r requirements-test.txt --format json

            - name: Upload snyk result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@main
              if: always()
              with:
                sarif_file: snyk.sarif
