# -------------------------------------------------------
#!/bin/bash
# -------------------------------------------------------
# TECHNOGIX
# -------------------------------------------------------
# Copyright (c) [2022] Technogix SARL
# All rights reserved
# -------------------------------------------------------
# Release pipeline for robotframework keywords
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 01 march 2022
# -------------------------------------------------------

name: Keywords Release Pipeline

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

    check:
        name: Analyze Package
        runs-on: ubuntu-latest
        container: technogix/terraform-python-awscli:v1.1.0
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Linting module
              uses: docker://technogix/terraform-python-awscli:v1.1.0
              with:
                args: pylint keywords tools

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/python@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Run pip-audit to check for vulnerabilities
              uses: docker://technogix/terraform-python-awscli:v1.1.0
              with:
                args: pip-audit requirements-test.txt

            - name: Upload snyk result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: snyk.sarif